# Copyright 2018-2021 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_crypto"
version = "0.16.0"
edition = "2018"
description = "Web Cryptography API implementation for Deno"
authors = ["the Deno authors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/denoland/deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core = { version = "0.82.0", path = "../../core" }
rand = "0.8.3"
ring = "0.16.19"
tokio = { version = "1.1.1", features = ["full"] }
serde_json = { version = "1.0.62", features = ["preserve_order"] }
serde = { version = "1.0.123", features = ["derive"] }
